<a href="https://colab.research.google.com/github/reidnersousa/IFB_OPT3_Machine-Learning_2023-2/blob/main/aula07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

import pandas as pd

# Dados fornecidos
data = {
    'Country': ['France', 'Spain', 'Germany', 'Spain', 'Germany', 'France', 'Spain', 'France', 'Germany', 'France'],
    'Age': [44, 27, 30, 38, 40, 35, None, 48, 50, 37],
    'Salary': [72000, 48000, 54000, 61000, None, 58000, 57200, 79000, 83000, 67000],
    'Purchased': ['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes']
}

# Criar um DataFrame do pandas
df = pd.DataFrame(data)

# Salvar os dados em um arquivo CSV
df.to_csv('dados.csv', index=False)

print('Arquivo CSV criado com sucesso.')


Arquivo CSV criado com sucesso.


In [ ]:
dados = pd.read_csv('dados.csv')

dados.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [ ]:
#DataFrame.iloc[linhas, colunas]
entrada = dados.iloc[:,:-1].values
saida   = dados.iloc[:,-1].values


print(entrada)
print()
print(saida)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 57200.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


colocando valores ausente

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan ,strategy ='mean')
imputer = imputer.fit(entrada[:,1:3])
entrada[:,1:3] = imputer.transform(entrada[:,1:3])

entrada

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 64355.555555555555],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 57200.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
print(entrada[:,0])

['France' 'Spain' 'Germany' 'Spain' 'Germany' 'France' 'Spain' 'France'
 'Germany' 'France']


In [ ]:
from sklearn.preprocessing import LabelEncoder ,OneHotEncoder
from sklearn.compose import ColumnTransformer
labelencoder_entrada = LabelEncoder()


# entrada[:,0:1] = labelencoder_entrada.fit_transform(entrada[:,0:1])
entrada[:,0] = labelencoder_entrada.fit_transform(entrada[:,0])
print(entrada)
print()
ct  = ColumnTransformer([("Country",OneHotEncoder(),[0])],remainder='passthrough')

entrada = ct.fit_transform(entrada)

entrada

## 1.0 0.0 0.0 France
## 0.0 0.0 1.0 Spain
## 0.0 1.0 0.0 Germany

[[0 1.0 0.0 0.0 44.0 72000.0]
 [1 0.0 0.0 1.0 27.0 48000.0]
 [1 0.0 1.0 0.0 30.0 54000.0]
 [1 0.0 0.0 1.0 38.0 61000.0]
 [1 0.0 1.0 0.0 40.0 64355.555555555555]
 [0 1.0 0.0 0.0 35.0 58000.0]
 [1 0.0 0.0 1.0 38.77777777777778 57200.0]
 [0 1.0 0.0 0.0 48.0 79000.0]
 [1 0.0 1.0 0.0 50.0 83000.0]
 [0 1.0 0.0 0.0 37.0 67000.0]]



array([[1.0, 0.0, 1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 1.0, 0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 1.0, 0.0, 40.0, 64355.555555555555],
       [1.0, 0.0, 1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 1.0, 0.0, 0.0, 1.0, 38.77777777777778, 57200.0],
       [1.0, 0.0, 1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [ ]:
label_encoder_saida =LabelEncoder()
saida = label_encoder_saida.fit_transform(saida)
saida

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
from sklearn.model_selection import  train_test_split

#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,random_state = 0)
entrada_train ,entrada_test ,saida_train , saida_test = train_test_split(entrada,saida,test_size =0.2 ,random_state=0)

Padronização dos dados de entrada: Os dados de entrada são padronizados usando o StandardScaler, o que significa que eles são transformados para terem média zero e desvio padrão igual a 1. Isso é comum em muitos algoritmos de aprendizado de máquina, pois ajuda a melhorar o desempenho do modelo.

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_entrada = StandardScaler()
entrada_train = sc_entrada.fit_transform(entrada_train)
entrada_test = sc_entrada.transform(entrada_test)
print(entrada_train)
print()
entrada_test
#StandardScaler()


[[-1.          2.64575131 -0.77459667  0.26306757  0.1156907 ]
 [ 1.         -0.37796447 -0.77459667 -0.25350148  0.41096562]
 [-1.         -0.37796447  1.29099445 -1.97539832 -1.71054746]
 [-1.         -0.37796447  1.29099445  0.05261351 -0.6832885 ]
 [ 1.         -0.37796447 -0.77459667  1.64058505  1.75086862]
 [-1.         -0.37796447  1.29099445 -0.0813118  -0.25898588]
 [ 1.         -0.37796447 -0.77459667  0.95182631  0.96925854]
 [ 1.         -0.37796447 -0.77459667 -0.59788085 -0.59396163]]



array([[-1.        ,  2.64575131, -0.77459667, -1.45882927, -1.04059596],
       [-1.        ,  2.64575131, -0.77459667,  1.98496442,  2.19750295]])

treinamento

Avaliação do modelo